import React from 'react';
import { motion } from 'framer-motion';
import { BookOpen } from 'lucide-react';

const ResearchPapers = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
  };

  const papers = [
    {
      title: "Deepfake Detection Using Spatiotemporal Convolutional Networks",
      authors: "Guera, D., & Delp, E. J.",
      year: "2018",
      abstract: "This paper proposes a temporal-aware pipeline to automatically detect deepfake videos using a recurrent convolutional neural network (RCN).",
      link: "#"
    },
    {
      title: "FaceForensics++: Learning to Detect Manipulated Facial Images",
      authors: "Rossler, A., et al.",
      year: "2019",
      abstract: "A large-scale dataset of manipulated facial imagery and a comprehensive study of state-of-the-art detection methods.",
      link: "#"
    },
    {
      title: "Detecting AI-Generated Audio using MFCC and Spectral Analysis",
      authors: "AI Guardian Research Team",
      year: "2024",
      abstract: "Our proprietary research on distinguishing synthetic voice patterns by analyzing high-frequency spectral artifacts.",
      link: "#"
    },
    {
      title: "Transformer-Based Approaches for Text Generation Detection",
      authors: "AI Guardian Research Team",
      year: "2024",
      abstract: "Evaluating the efficacy of BERT and Roberta models in identifying text generated by Large Language Models (LLMs).",
      link: "#"
    }
  ];

  return (
    <div className="max-w-6xl mx-auto px-4 py-12 relative z-10">
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="space-y-12"
      >
        <motion.div variants={itemVariants} className="text-center space-y-4">
          <div className="inline-block p-4 rounded-full bg-pink-500/10 border border-pink-500/30 mb-4">
            <BookOpen size={48} className="text-pink-400" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white">Research Papers</h1>
          <p className="text-xl text-slate-400 max-w-2xl mx-auto">
            Exploring the science behind digital forensics and synthetic media detection.
          </p>
        </motion.div>

        <div className="grid gap-6">
          {papers.map((paper, index) => (
            <motion.div 
              key={index}
              variants={itemVariants}
              className="cyber-card group hover:border-pink-500/50 transition-colors"
            >
              <div className="flex flex-col md:flex-row justify-between md:items-start gap-4">
                <div className="space-y-2 flex-1">
                  <h2 className="text-xl font-bold text-white group-hover:text-pink-400 transition-colors">
                    {paper.title}
                  </h2>
                  <p className="text-sm text-cyber-accent font-mono">
                    {paper.authors} • {paper.year}
                  </p>
                  <p className="text-slate-400 leading-relaxed">
                    {paper.abstract}
                  </p>
                </div>
                <div className="flex gap-2 mt-4 md:mt-0">
                  <button className="flex items-center gap-2 px-4 py-2 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 text-sm transition-colors border border-slate-700 hover:border-pink-500/50 hover:text-pink-400">
                    <BookOpen size={16} />
                    <span>Read Me</span>
                  </button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

export default ResearchPapers;
